### PR TITLE
download mysream from yandex cdn

### PR DESCRIPTION
**Pull request by ZigGreen**
download mysream from yandex cdn on postinstall script
add start method

### CODE REVIEW

**Comment by titarenko** [comment]
Thank you for this PR! I'll try to merge within couple of days.

**Comment by ZigGreen** [comment]
cool!
if the module has api like listed below it'll be great for user experience 

``` js
var MyStem = require('mystem-wrapper');
var mystem = MyStem(MyStemProcOptions);
mystem.start();
mystem
    .analyze('Жили у бабуси два веселых гуся.')
    .then(console.log)
    .catch(console.error)
    .finally(mystem.close);
```

**Comment by titarenko** [comment]
Hi, 

I did merge, but with some edits related to mystem installation and wrapper API. 

I preferred to preserve initial API, but allowed passing custom arguments via builder function. Please see updated `README` for example.

**Comment by titarenko** [comment]
And, of course, new version (0.2.0) is published to NPM.

**Pull request merged**
